[metadata]
description-file = README.md

[flake8]
max-complexity = 10
exclude = .git,.tox,__pycache__,pyenv,build,dist
# set to true to check all ignored errors
disable_noqa = False

# adaptions for black
max-line-length = 88
extend-ignore = E203

[mypy]
python_version = 3.9
warn_return_any = False
warn_unused_configs = True
disallow_untyped_defs = False
disallow_incomplete_defs = False
check_untyped_defs = True
disallow_untyped_calls = False
disallow_untyped_decorators = False
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = False
warn_no_return = False
strict_equality = True
extra_checks = True

[mypy-xmltodict.*]
ignore_missing_imports = True

[mypy-osmapi.node]
disable_error_code = misc

[mypy-osmapi.way]
disable_error_code = misc

[mypy-osmapi.relation]
disable_error_code = misc

[mypy-osmapi.changeset]
disable_error_code = misc

[mypy-osmapi.note]
disable_error_code = misc

[mypy-osmapi.capabilities]
disable_error_code = misc
