"""
HTTP session management for the OpenStreetMap API.
"""

import datetime
import itertools as it
import logging
import requests
import time
from typing import Any

from . import errors

logger = logging.getLogger(__name__)


class OsmApiSession:
    MAX_RETRY_LIMIT = 5
    """Maximum retries if a call to the remote API fails (default: 5)"""

    def __init__(
        self,
        base_url: str,
        created_by: str,
        session: requests.Session | None = None,
        timeout: int = 30,
    ) -> None:
        self._api = base_url
        self._created_by = created_by
        self._timeout = timeout

        # authentication is taken from the session (e.g. an OAuth 2.0 session)
        self._auth: Any = getattr(session, "auth", None)

        # A caller-provided session can carry credentials in ways that are not
        # visible from the outside: `session.auth`, an `Authorization` header,
        # a custom transport adapter, or a `Session` subclass adding the token
        # per request (this is what requests-oauthlib does). Sniffing
        # `session.auth` therefore both rejects valid setups and accepts
        # sessions without any token, so it is not used to make this decision:
        # the only case in which authentication is certainly missing is a
        # session that was built here, i.e. one the caller didn't provide.
        # Everything else is sent, and the API answers with a 401 ->
        # `UnauthorizedApiError` if the authorization really was missing.
        self._can_authenticate: bool = session is not None

        self._http_session = session
        self._session = self._get_http_session()

    def close(self) -> None:
        if self._session:
            self._session.close()

    def _http_request(  # noqa: C901
        self,
        method: str,
        path: str,
        auth: bool,
        send: str | bytes | None,
        return_value: bool = True,
        params: dict | None = None,
    ) -> bytes:
        """
        Returns the response generated by an HTTP request.

        `method` is a HTTP method to be executed
        with the request data. For example: 'GET' or 'POST'.
        `path` is the path to the requested resource relative to the
        base API address stored in self._api. Should start with a
        slash character to separate the URL.
        `auth` is a boolean indicating whether authentication should
        be preformed on this request.
        `send` contains additional data that might be sent in a
        request.
        `return_value` indicates wheter this request should return
        any data or not.

        If the request requires authentication and no session was provided to
        carry credentials, `OsmApi.AuthenticationMissingError` is raised. With
        a session, the request is sent and a rejected authorization surfaces
        as `OsmApi.UnauthorizedApiError` (HTTP 401).

        If the requested element has been deleted,
        `OsmApi.ElementDeletedApiError` is raised.

        If the requested element can not be found,
        `OsmApi.ElementNotFoundApiError` is raised.

        If the response status code indicates an error,
        `OsmApi.ApiError` is raised.
        """
        logger.debug(f"{datetime.datetime.now():%Y-%m-%d %H:%M:%S} {method} {path}")

        # Add API base URL to path
        path = self._api + path

        if auth and not self._can_authenticate:
            raise errors.AuthenticationMissingError(
                "Authentication missing, this request requires an "
                "authenticated session, but no session was provided "
                "(see the OAuth 2.0 examples)"
            )

        try:
            response = self._session.request(
                method, path, data=send, timeout=self._timeout, params=params
            )
        except requests.exceptions.Timeout as e:
            raise errors.TimeoutApiError(
                0, f"Request timed out (timeout={self._timeout})", ""
            ) from e
        except requests.exceptions.ConnectionError as e:
            raise errors.ConnectionApiError(0, f"Connection error: {str(e)}", "") from e
        except requests.exceptions.RequestException as e:
            raise errors.ApiError(0, str(e), "") from e

        if response.status_code != 200:
            payload = response.content.strip()
            if response.status_code == 401:
                raise errors.UnauthorizedApiError(
                    response.status_code, response.reason, payload
                )
            if response.status_code == 404:
                raise errors.ElementNotFoundApiError(
                    response.status_code, response.reason, payload
                )
            elif response.status_code == 410:
                raise errors.ElementDeletedApiError(
                    response.status_code, response.reason, payload
                )
            raise errors.ApiError(response.status_code, response.reason, payload)
        if return_value and not response.content:
            raise errors.ResponseEmptyApiError(
                response.status_code, response.reason, ""
            )

        logger.debug(f"{datetime.datetime.now():%Y-%m-%d %H:%M:%S} {method} {path}")
        return response.content

    def _http(  # type: ignore[return-value]  # noqa: C901
        self,
        cmd: str,
        path: str,
        auth: bool,
        send: str | bytes | None,
        return_value: bool = True,
        params: dict | None = None,
    ) -> bytes:
        for i in it.count(1):
            try:
                return self._http_request(
                    cmd, path, auth, send, return_value=return_value, params=params
                )
            except errors.ApiError as e:
                if e.status >= 500:
                    if i == self.MAX_RETRY_LIMIT:
                        raise
                    if i != 1:
                        self._sleep()
                    self._session = self._get_http_session()
                else:
                    logger.debug("ApiError Exception occured")
                    raise
            except errors.AuthenticationMissingError:
                raise
            except Exception as e:
                logger.exception("General exception occured")
                if i == self.MAX_RETRY_LIMIT:
                    if isinstance(e, errors.OsmApiError):
                        raise
                    raise errors.MaximumRetryLimitReachedError(
                        f"Give up after {i} retries"
                    ) from e
                if i != 1:
                    self._sleep()
                self._session = self._get_http_session()

    def _get_http_session(self) -> requests.Session:
        """
        Creates a requests session for connection pooling.
        """
        if self._http_session:
            session = self._http_session
        else:
            session = requests.Session()

        session.auth = self._auth
        session.headers.update({"user-agent": self._created_by})
        return session

    def _sleep(self) -> None:
        time.sleep(5)

    def _get(self, path: str, params: dict | None = None) -> bytes:
        return self._http("GET", path, False, None, params=params)

    def _put(
        self, path: str, data: str | bytes | None, return_value: bool = True
    ) -> bytes:
        return self._http("PUT", path, True, data, return_value=return_value)

    def _post(
        self,
        path: str,
        data: str | bytes | None,
        optionalAuth: bool = False,
        forceAuth: bool = False,
        params: dict | None = None,
    ) -> bytes:
        # the Notes API allows certain POSTs by non-authenticated users
        auth = optionalAuth and self._can_authenticate
        if forceAuth:
            auth = True
        return self._http("POST", path, bool(auth), data, params=params)

    def _delete(self, path: str, data: str | bytes | None) -> bytes:
        return self._http("DELETE", path, True, data)
